# Pandas

In [ ]:
# https://pandas.pydata.org/docs/user_guide/index.html#user-guide

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels= ['a','b','c']
mylist = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [5]:
pd.Series(data = mylist, index = labels) # pd.Series(mylist,labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [9]:
salesQ1 = pd.Series(data = [250,450,200,150], index = ['USA','China', 'India', 'Brazil'])

In [11]:
salesQ2 = pd.Series(data = [260,500,210,100], index = ['USA','China', 'India', 'Japan'])

In [24]:
salesQ2['USA'] # You can do both call by index or name

260

In [26]:
salesQ2.iloc[0] # Better than salesQ2[0]  Error if you surpass the length

260

In [29]:
salesQ1 + salesQ2 #Only to check if both have the same index, not sum correctly anyways

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

## DataFrames

In [30]:
import numpy as np
import pandas as pd

In [32]:
columns = ['W','X','Y','Z']

In [35]:
index = ['A','B','C','D','E']

In [36]:
from numpy.random import randint

In [39]:
np.random.seed(42)
data = randint(-100,100,(5,4))

In [40]:
data

array([[  2,  79,  -8, -86],
       [  6, -29,  88, -80],
       [  2,  21, -26, -13],
       [ 16,  -1,   3,  51],
       [ 30,  49, -48, -99]])

In [41]:
df = pd.DataFrame( data=data,index = index,columns = columns)

In [42]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

### Columns

In [45]:
type(df['W'])

pandas.core.series.Series

In [47]:
df['W']

A     2
B     6
C     2
D    16
E    30
Name: W, dtype: int32

In [49]:
df[['W','Z']] #List of columns

    W   Z
A   2 -86
B   6 -80
C   2 -13
D  16  51
E  30 -99

In [57]:
df['new'] = df['W'] +df['Y'] # Add columns

In [52]:
df

    W   X   Y   Z  new
A   2  79  -8 -86   -6
B   6 -29  88 -80   94
C   2  21 -26 -13  -24
D  16  -1   3  51   19
E  30  49 -48 -99  -18

In [53]:
df.drop('new', axis = 1) # Drop the entire column not the index, not permanent

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [58]:
df = df.drop('new', axis = 1) #Permanent

### Rows

In [63]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [59]:
df.loc['A']

W     2
X    79
Y    -8
Z   -86
Name: A, dtype: int32

In [60]:
df.loc[['A','E']]

    W   X   Y   Z
A   2  79  -8 -86
E  30  49 -48 -99

In [64]:
df.iloc[0:3] # Position instead of name -1 last row

   W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80
C  2  21 -26 -13

In [65]:
df.drop('C') #Not permanent

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
D  16  -1   3  51
E  30  49 -48 -99

### Both

In [68]:
df.loc[['A','C'],['W','Y']]

   W   Y
A  2  -8
C  2 -26

### Conditions

In [69]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [70]:
df > 0

      W      X      Y      Z
A  True   True  False  False
B  True  False   True  False
C  True   True  False  False
D  True  False   True   True
E  True   True  False  False

In [71]:
df[df>0]

    W     X     Y     Z
A   2  79.0   NaN   NaN
B   6   NaN  88.0   NaN
C   2  21.0   NaN   NaN
D  16   NaN   3.0  51.0
E  30  49.0   NaN   NaN

In [72]:
df['X'] > 0

A     True
B    False
C     True
D    False
E     True
Name: X, dtype: bool

In [73]:
df[df['X'] > 0] # New datset and i can do anything

    W   X   Y   Z
A   2  79  -8 -86
C   2  21 -26 -13
E  30  49 -48 -99

In [74]:
df[df['X'] > 0]['W'] #.iloc

A     2
C     2
E    30
Name: W, dtype: int32

In [79]:
df[(df['W'] > 0) & (df['Y'] > 1)] # & |

    W   X   Y   Z
B   6 -29  88 -80
D  16  -1   3  51

In [81]:
df.reset_index() #Not permanent

  index   W   X   Y   Z
0     A   2  79  -8 -86
1     B   6 -29  88 -80
2     C   2  21 -26 -13
3     D  16  -1   3  51
4     E  30  49 -48 -99

In [82]:
new_ind = ['CA','NY','WY','OR','CO']

In [83]:
df['States'] = new_ind

In [84]:
df

    W   X   Y   Z States
A   2  79  -8 -86     CA
B   6 -29  88 -80     NY
C   2  21 -26 -13     WY
D  16  -1   3  51     OR
E  30  49 -48 -99     CO

In [88]:
df = df.set_index('States') # New indexs, delete A,B,C,D,E

In [91]:
df

         W   X   Y   Z
States
CA       2  79  -8 -86
NY       6 -29  88 -80
WY       2  21 -26 -13
OR      16  -1   3  51
CO      30  49 -48 -99

In [92]:
df.describe()

              W          X          Y          Z
count   5.00000   5.000000   5.000000   5.000000
mean   11.20000  23.800000   1.800000 -45.400000
std    11.96662  42.109381  51.915316  63.366395
min     2.00000 -29.000000 -48.000000 -99.000000
25%     2.00000  -1.000000 -26.000000 -86.000000
50%     6.00000  21.000000  -8.000000 -80.000000
75%    16.00000  49.000000   3.000000 -13.000000
max    30.00000  79.000000  88.000000  51.000000

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      int32
 1   X       5 non-null      int32
 2   Y       5 non-null      int32
 3   Z       5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes

In [99]:
df.dtypes

W    int32
X    int32
Y    int32
Z    int32
dtype: object

### Missing Data

In [102]:
# Leave anyways
# Filling missing data mean,median,reasonable value
# Remove

In [103]:
import numpy as np
import pandas as pd

In [124]:
df = pd.DataFrame({'A':[1,2,np.nan,4], 'B':[5,np.nan,np.nan,8], 'C':[10,20,30,40]})

In [108]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [109]:
df.dropna() #Delete rows with nan

     A    B   C
0  1.0  5.0  10
3  4.0  8.0  40

In [110]:
df.dropna(axis = 1) #Delete columns with nan

    C
0  10
1  20
2  30
3  40

In [111]:
df.dropna(axis = 1, thresh = 2) # Como maximo 2 nan usar un porcentaje

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [119]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [118]:
df.fillna(value='Fill Value') #value = 0

            A           B   C
0         1.0         5.0  10
1         2.0  Fill Value  20
2  Fill Value  Fill Value  30
3         4.0         8.0  40

In [121]:
df['A'] = df['A'].fillna(value = 0)

In [122]:
df['B'].fillna(value = df['B'].mean())

0    5.0
1    6.5
2    6.5
3    8.0
Name: B, dtype: float64

In [125]:
df.fillna(df.mean())

          A    B   C
0  1.000000  5.0  10
1  2.000000  6.5  20
2  2.333333  6.5  30
3  4.000000  8.0  40

### Group By

In [126]:
import pandas as pd

In [133]:
df = pd.read_csv("Universities.csv")

In [129]:
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

In [136]:
type(df.groupby('Year').sum())

pandas.core.frame.DataFrame

In [140]:
df.groupby('Year').sum().sort_index(ascending= False)

,Sector,University,Completions,Geography
Year,,,,
2016,"Private for-profit, 2-yearPrivate for-profit, ...",Pima Medical Institute-Las VegasHealthcare Pre...,26224,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2015,"Private for-profit, 2-yearPrivate not-for-prof...",Pima Medical Institute-Las VegasRoseman Univer...,26279,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2014,"Private not-for-profit, 4-year or abovePrivate...",Roseman University of Health SciencesExpertise...,24730,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2013,"Private for-profit, 2-yearPrivate for-profit, ...",Aviation Institute of Maintenance-Las VegasDeV...,21046,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
2012,"Private for-profit, less-than 2-yearPrivate fo...",Academy of Hair Design-Las VegasCareer College...,20333,NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...

In [141]:
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

In [142]:
df.groupby(['Year','Sector']).sum() #Doble agrupacion

                                                                                     University  \
Year Sector
2012 Private for-profit, 2-year               Career College of Northern NevadaPaul Mitchell...
     Private for-profit, 4-year or above      Sanford-Brown College-Las VegasITT Technical I...
     Private for-profit, less-than 2-year     Academy of Hair Design-Las VegasMilan Institut...
     Private not-for-profit, 2-year           Everest College-HendersonExpertise Cosmetology...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesTouro Uni...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  University of Nevada-RenoCollege of Southern N...
2013 Private for-profit, 2-year               Aviation Institute of Maintenance-Las VegasCar...
     Private for-profit, 4-year or above      DeVry University-NevadaITT Technical Institute...
     Private for-profit, less-than 2-year     Academy of Hair Design-Las VegasMilan Institut...
     Private not-for-profit, 2-year           Expertise Cosmetology InstituteEverest College...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesTouro Uni...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  University of Nevada-RenoUniversity of Nevada-...
2014 Private for-profit, 2-year               Nevada Career InstituteEuphoria Institute of B...
     Private for-profit, 4-year or above      Sanford-Brown College-Las VegasThe Art Institu...
     Private for-profit, less-than 2-year     Healthcare Preparatory InstituteMilan Institut...
     Private not-for-profit, 2-year           Expertise Cosmetology InstituteEverest College...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesSierra Ne...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  College of Southern NevadaWestern Nevada Colle...
2015 Private for-profit, 2-year               Pima Medical Institute-Las VegasBrightwood Col...
     Private for-profit, 4-year or above      ITT Technical Institute-Las VegasUniversity of...
     Private for-profit, less-than 2-year     Milan Institute-SparksHealthcare Preparatory I...
     Private not-for-profit, 2-year           Everest College-HendersonExpertise Cosmetology...
     Private not-for-profit, 4-year or above  Roseman University of Health SciencesSierra Ne...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  University of Nevada-Las VegasGreat Basin Coll...
2016 Private for-profit, 2-year               Pima Medical Institute-Las VegasNorthwest Care...
     Private for-profit, 4-year or above      University of Phoenix-NevadaChamberlain Colleg...
     Private for-profit, less-than 2-year     Healthcare Preparatory InstituteMilan Institut...
     Private not-for-profit, 2-year           Everest College-HendersonExpertise Cosmetology...
     Private not-for-profit, 4-year or above  Sierra Nevada CollegeWongu University of Orien...
     Public, 2-year                                           Truckee Meadows Community College
     Public, 4-year or above                  Western Nevada CollegeGreat Basin CollegeNevad...

                                              Completions  \
Year Sector
2012 Private for-profit, 2-year                      3072
     Private for-profit, 4-year or above              632
     Private for-profit, less-than 2-year            1327
     Private not-for-profit, 2-year                   665
     Private not-for-profit, 4-year or above         1059
     Public, 2-year                                  1170
     Public, 4-year or above                        12408
2013 Private for-profit, 2-year                      3053
     Private for-profit, 4-year or above              775
     Private for-profit, less-than 2-year            1281
     Private not-for-profit, 2-year                   471
     Private not-for-profit, 4-year or above         1016
     Public, 2-year                                  1633
     Public, 4-year or above                        12817
2014 Private for-profit, 2-year                      2957
     Private for-profit, 4-year or above             1506
     Private for-profit, less-than 2-year            1328
     Private not-for-profit, 2-year                   449
     Private not-for-profit, 4-year or above         1042
     Public, 2-year                                  2286
     Public, 4-year or above                        15162
2015 Private for-profit, 2-year                      3280
     Private for-profit, 4-year or above             1306
     Private for-profit, less-than 2-year            1629
     Private not-for-profit, 2-year                   425
     Private not-for-profit, 4-year or above         1228
     Public, 2-year                                  2355
     Public, 4-year or above                        16056
2016 Private for-profit, 2-year                      3286
     Private for-profit, 4-year or above              748
     Private for-profit, less-than 2-year            1552
     Private not-for-profit, 2-year                   322
     Private not-for-profit, 4-year or above         1208
     Public, 2-year                                  2431
     Public, 4-year or above                        16677

                                                                                      Geography
Year Sector
2012 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                               NevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year            NevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2013 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                         NevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year            NevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2014 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                   NevadaNevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year      NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2015 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above       NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year      NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                                 NevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada
2016 Private for-profit, 2-year               NevadaNevadaNevadaNevadaNevadaNevadaNevadaNeva...
     Private for-profit, 4-year or above                   NevadaNevadaNevadaNevadaNevadaNevada
     Private for-profit, less-than 2-year      NevadaNevadaNevadaNevadaNevadaNevadaNevadaNevada
     Private not-for-profit, 2-year                                                NevadaNevada
     Private not-for-profit, 4-year or above                           NevadaNevadaNevadaNevada
     Public, 2-year                                                                      Nevada
     Public, 4-year or above                               NevadaNevadaNevadaNevadaNevadaNevada

In [144]:
df.groupby('Year').describe() # .transpose()

Year                      2012         2013         2014         2015  \
Completions count    38.000000    40.000000    42.000000    44.000000
            mean    535.078947   526.150000   588.809524   597.250000
            std    1036.433239  1040.474782  1150.355857  1183.371791
            min      13.000000     0.000000     0.000000     0.000000
            25%     114.250000    98.500000   104.500000    87.750000
            50%     229.500000   189.000000   203.500000   191.000000
            75%     420.500000   413.000000   371.750000   405.750000
            max    5388.000000  5278.000000  5093.000000  5335.000000

Year                      2016
Completions count    43.000000
            mean    609.860465
            std    1235.952796
            min       0.000000
            25%      90.000000
            50%     208.000000
            75%     414.000000
            max    5367.000000

### Operations

In [145]:
import pandas as pd
df_one = pd.DataFrame({'k1':['A','A','B','B','C','C'],
                      'col1':[100,200,300,300,400,500],
                      'col2':['NY','CA','WA','WA','AK','NV']})

In [146]:
df_one

  k1  col1 col2
0  A   100   NY
1  A   200   CA
2  B   300   WA
3  B   300   WA
4  C   400   AK
5  C   500   NV

In [151]:
df_one['col2'].unique() #Elementos unicos

array(['NY', 'CA', 'WA', 'AK', 'NV'], dtype=object)

In [150]:
df_one['k1'].nunique() #Numero

3

In [152]:
df_one['col2'].value_counts()

col2
WA    2
NY    1
CA    1
AK    1
NV    1
Name: count, dtype: int64

In [153]:
df_one.drop_duplicates()

  k1  col1 col2
0  A   100   NY
1  A   200   CA
2  B   300   WA
4  C   400   AK
5  C   500   NV

In [156]:
df_one['NEW'] = df_one['col1'] * 10

In [157]:
df_one

  k1  col1 col2   NEW
0  A   100   NY  1000
1  A   200   CA  2000
2  B   300   WA  3000
3  B   300   WA  3000
4  C   400   AK  4000
5  C   500   NV  5000

In [159]:
def grab_first_letter(state):
    return state[0]

In [160]:
grab_first_letter('tresd0')

't'

In [163]:
df_one['fisrt letter'] = df_one['col2'].apply(grab_first_letter)

In [164]:
df_one

  k1  col1 col2   NEW fisrt letter
0  A   100   NY  1000            N
1  A   200   CA  2000            C
2  B   300   WA  3000            W
3  B   300   WA  3000            W
4  C   400   AK  4000            A
5  C   500   NV  5000            N

In [165]:
def complex_letter(state):
    
    if state[0] == "W":
        return "Washington"
    else:
        return 'Error'

#Error for any different a string

In [166]:
df_one['col2'].apply(complex_letter)

0         Error
1         Error
2    Washington
3    Washington
4         Error
5         Error
Name: col2, dtype: object

In [167]:
df_one['k1']

0    A
1    A
2    B
3    B
4    C
5    C
Name: k1, dtype: object

In [169]:
my_map = {'A':1,'B':2,'C':3}

In [171]:
df_one['num'] = df_one['k1'].map(my_map) # Converitr las A en 1

In [172]:
df_one

  k1  col1 col2   NEW fisrt letter  num
0  A   100   NY  1000            N    1
1  A   200   CA  2000            C    1
2  B   300   WA  3000            W    2
3  B   300   WA  3000            W    2
4  C   400   AK  4000            A    3
5  C   500   NV  5000            N    3

In [177]:
df_one.max() #Elemento

k1                 C
col1             500
col2              WA
NEW             5000
fisrt letter       W
num                3
dtype: object

In [176]:
df_one.idxmax() #Indice

k1              4
col1            5
col2            2
NEW             5
fisrt letter    2
num             4
dtype: int64

In [178]:
df_one.columns

Index(['k1', 'col1', 'col2', 'NEW', 'fisrt letter', 'num'], dtype='object')

In [181]:
df_one.columns = ['C1','C2','C3','C4','C5','C6']

In [182]:
df_one.columns

Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6'], dtype='object')

In [184]:
df_one.sort_values('C3', ascending = False) #Same index

  C1   C2  C3    C4 C5  C6
2  B  300  WA  3000  W   2
3  B  300  WA  3000  W   2
0  A  100  NY  1000  N   1
5  C  500  NV  5000  N   3
1  A  200  CA  2000  C   1
4  C  400  AK  4000  A   3

### Join DataFrame

In [185]:
features = pd.DataFrame({'A':[100,200,300,400,500],
                        'B':[12,13,14,15,16]})
predictions = pd.DataFrame({'pred':[0,1,1,0,1]})

In [186]:
features

     A   B
0  100  12
1  200  13
2  300  14
3  400  15
4  500  16

In [187]:
predictions

   pred
0     0
1     1
2     1
3     0
4     1

In [189]:
pd.concat([features,predictions], axis = 1) #Por columnas

     A   B  pred
0  100  12     0
1  200  13     1
2  300  14     1
3  400  15     0
4  500  16     1

### Dummies

In [190]:
df_one

  C1   C2  C3    C4 C5  C6
0  A  100  NY  1000  N   1
1  A  200  CA  2000  C   1
2  B  300  WA  3000  W   2
3  B  300  WA  3000  W   2
4  C  400  AK  4000  A   3
5  C  500  NV  5000  N   3

In [191]:
df_one['C1']

0    A
1    A
2    B
3    B
4    C
5    C
Name: C1, dtype: object

In [192]:
pd.get_dummies(df_one['C1']) #Not permanent

       A      B      C
0   True  False  False
1   True  False  False
2  False   True  False
3  False   True  False
4  False  False   True
5  False  False   True

### Read Data

https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

In [3]:
import numpy as np
import pandas as pd

In [5]:
pwd #File path you are currently in

'C:\\Users\\Pedro Delgado Jiméne\\Desktop'

In [13]:
df = pd.read_csv('C:\\Users\\Pedro Delgado Jiméne\\Desktop\\example.csv') #Always do right

In [12]:
ls  # Ver que hay en pwd directory con el comentario no funciona correctamente

 El volumen de la unidad C no tiene etiqueta.
 El n£mero de serie del volumen es: 3248-1FB3

 Directorio de C:\Users\Pedro Delgado Jim‚ne\Desktop

03/10/2024  12:10    <DIR>          .
24/09/2024  12:14    <DIR>          ..
02/10/2024  12:55    <DIR>          .ipynb_checkpoints
27/09/2024  09:27    <DIR>          __pycache__
26/08/2024  17:27    <DIR>          2024?
05/08/2024  20:22    <DIR>          Adobe
23/08/2024  18:48    <DIR>          Carnet
03/10/2024  11:26            54.381 Chapter4.ipynb
01/10/2024  17:46            16.165 Cuento 1.docx
04/09/2024  18:40           129.426 documentacion maste.png
01/10/2024  13:45    <DIR>          Esquema Data Science
30/09/2024  23:54    <DIR>          Esquema ML Engineer
02/10/2024  17:44         2.330.365 Foto.png
24/09/2024  12:17             1.698 jupyter-notebook.lnk
25/09/2024  19:12    <DIR>          Kaggle
01/10/2024  11:21    <DIR>          Libro
24/04/2024  19:04             1.174 MEGAsync.lnk
23/09/2024  21:23            97.020 Open AI requisitos.png
03/10/2024  12:10           143.554 Pandas.ipynb
01/10/2024  12:06            16.810 Universities.csv
06/09/2024  18:19             1.449 Visual Studio Code.lnk
              10 archivos      2.792.042 bytes
              11 dirs  891.975.073.792 bytes libres

In [16]:
df.to_csv('example1.csv', index = True)

In [17]:
pd.read_csv('example1.csv')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Leer html

In [21]:
tables = pd.read_html('https://datitos.github.io/curso-aprendizaje-profundo/2021/')

In [23]:
type(tables) # List

list

In [27]:
tables[0] # == tables no existe tables[1]

,Unnamed: 0,Fecha,Descripción,Libro,Unnamed: 4
0,Clase 1,Lunes 15 de marzo,"Introducción, motivación y bienvenida Definic...","Capítulo 1 ""Introduction""",Presentación Video
1,Clase 2,Miércoles 17 de marzo,Implementación de modelos Frameworks de apren...,"Capítulo 2 ""Preliminaries""",Presentación Video
2,Trabajo práctico 1,Miércoles 17 de marzo,Habilitado para resolución,NaN,Notebook
3,Consulta Pablo Marinozi,Jueves 18 de marzo,17:00 a 19:00,NaN,NaN
4,Consulta Luciano Robino,Viernes 19 de marzo,8:00 a 10:00,NaN,NaN
...,...,...,...,...,...
73,Consulta Pablo Marinozi,Jueves 15 de julio,17:00 a 19:00,NaN,NaN
74,Consulta Luciano Robino,Viernes 16 de julio,8:00 a 10:00,NaN,NaN
75,Consulta Pablo Marinozi,Jueves 22 de julio,17:00 a 19:00,NaN,NaN
76,Consulta Luciano Robino,Viernes 23 de julio,8:00 a 10:00,NaN,NaN
77,Proyecto final,Miércoles 28 de julio,ENTREGA,NaN,Presentaciones Informes

In [ ]:
#Exercises